#!/usr/bin/env python3
"""Post-generation guardrail for the AI hero art.

`flux`-style image models intermittently bake garbled text into the artwork, or
resolve a style like De Stijl into a realistic image framed inside a graphic
border (a collage). Both are the failures the eval harness surfaced. This module
runs a single vision check on the generated bytes and returns a verdict so the
caller can regenerate before the bad frame reaches the wall.

It fails OPEN: any error inspecting the image returns ok=True, so the guardrail
can never block a board from rendering.
"""
import base64
import json
import urllib.request

from scripts.common import get_openrouter_api_key
from scripts.openrouter.network import urlopen_with_context


INSPECT_PROMPT = (
    "You are a strict QA check for a flat, minimal weather-poster illustration. "
    "Answer ONLY about the artwork itself. Return STRICT JSON, no markdown:\n"
    '{"has_text": <true if ANY letters, words, numbers, or garbled/fake '
    'lettering appear anywhere in the image>, '
    '"is_collage": <true if it is a collage, or a realistic/photographic image '
    "placed inside a graphic frame, border, grid, or block (two competing "
    'aesthetics in one image)>, '
    '"note": "<= 12 word reason>"}'
)


def _guardrail_model(settings):
    openrouter = settings.get("openrouter", {})
    return (
        settings.get("pipeline", {}).get("image_guardrail_model")
        or openrouter.get("image_tool_model")
        or openrouter.get("text_model")
    )


def inspect_art(image_bytes, settings):
    """Return {ok, has_text, is_collage, note}. Fails open on any error."""
    model = _guardrail_model(settings)
    api_key = get_openrouter_api_key(settings)
    if not model or not api_key:
        return {"ok": True, "skipped": "no model or key"}

    timeout = settings.get("pipeline", {}).get("image_guardrail_timeout_seconds", 15)
    url = settings["openrouter"]["base_url"].rstrip("/") + "/chat/completions"
    img_b64 = base64.b64encode(image_bytes).decode("ascii")
    body = {
        "model": model,
        "messages": [
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": INSPECT_PROMPT},
                    {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{img_b64}"}},
                ],
            }
        ],
        "temperature": 0,
        "response_format": {"type": "json_object"},
    }
    request = urllib.request.Request(
        url=url,
        data=json.dumps(body).encode("utf-8"),
        method="POST",
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
    )
    try:
        with urlopen_with_context(request, timeout=timeout, settings=settings) as resp:
            payload = json.loads(resp.read().decode("utf-8"))
        content = payload["choices"][0]["message"]["content"].strip()
        if content.startswith("```"):
            content = content.split("```", 2)[1].lstrip("json").strip()
        verdict = json.loads(content)
    except Exception as error:  # noqa: BLE001 - guardrail must fail open
        return {"ok": True, "error": str(error)}

    has_text = bool(verdict.get("has_text"))
    is_collage = bool(verdict.get("is_collage"))
    return {
        "ok": not (has_text or is_collage),
        "has_text": has_text,
        "is_collage": is_collage,
        "note": verdict.get("note", ""),
    }
